// Input Sign UP Types
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_CONFIRM_PASSWORD = "CHANGE_CONFIRM_PASSWORD";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const RESET_SIGN_UP = "RESET_SIGN_UP";

// Input Login Types

export const CHANGE_LOGIN_PASSWORD = "CHANGE_LOGIN_PASSWORD";
export const CHANGE_LOGIN_EMAIL = "CHANGE_LOGIN_EMAIL";
export const RESET_LOGIN_DATA = "RESET_LOGIN_DATA";

// Register User Types

export const SUBMIT_REGISTER_DATA = "SUBMIT_REGISTER_DATA";
export const SUBMIT_REGISTER_DATA_SUCCESS = "SUBMIT_REGISTER_DATA_SUCCESS";
export const SUBMIT_REGISTER_DATA_ATTEMPT = "SUBMIT_REGISTER_DATA_ATTEMPT";
export const SUBMIT_REGISTER_DATA_FAIL = "SUBMIT_REGISTER_DATA_FAIL";

// GET Register User Types

export const GET_REGISTER_DATA = "GET_REGISTER_DATA";
export const GET_REGISTER_DATA_SUCCESS = "GET_REGISTER_DATA_SUCCESS";
export const GET_REGISTER_DATA_ATTEMPT = "GET_REGISTER_DATA_ATTEMPT";
export const GET_REGISTER_DATA_FAIL = "GET_REGISTER_DATA_FAIL";

// Login User Types

export const SUBMIT_LOGIN_DATA = "SUBMIT_LOGIN_DATA";
export const SUBMIT_LOGIN_DATA_SUCCESS = "SUBMIT_LOGIN_DATA_SUCCESS";
export const SUBMIT_LOGIN_DATA_ATTEMPT = "SUBMIT_LOGIN_DATA_ATTEMPT";
export const SUBMIT_LOGIN_DATA_FAIL = "SUBMIT_LOGIN_DATA_FAIL";
export const SIGN_OUT_USER = "SIGN_OUT_USER";

// Get Current Profile Actions

export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
export const GET_CURRENT_PROFILE_ATTEMPT = "GET_CURRENT_PROFILE_ATTEMPT";
export const GET_CURRENT_PROFILE_SUCCESS = "GET_CURRENT_PROFILE_SUCCESS";
export const GET_CURRENT_PROFILE_FAIL = "GET_CURRENT_PROFILE_FAIL";

// Submit Profile Constants

export const CHANGE_PROFILE_HANDLE = "CHANGE_PROFILE_HANDLE";
export const CHANGE_PROFILE_COMPANY = "CHANGE_PROFILE_COMPANY";
export const CHANGE_PROFILE_WEBSITE = "CHANGE_PROFILE_WEBSITE";
export const CHANGE_PROFILE_LOCATION = "CHANGE_PROFILE_LOCATION";
export const CHANGE_PROFILE_STATUS = "CHANGE_PROFILE_STATUS";
export const CHANGE_PROFILE_SKILLS = "CHANGE_PROFILE_SKILLS";
export const CHANGE_PROFILE_GITHUB_USERNAME = "CHANGE_PROFILE_GITHUB_USERNAME";
export const CHANGE_PROFILE_BIO = "CHANGE_PROFILE_BIO";
export const CHANGE_PROFILE_TWITTER = "CHANGE_PROFILE_TWITTER";
export const CHANGE_PROFILE_FACEBOOK = "CHANGE_PROFILE_FACEBOOK";
export const CHANGE_PROFILE_LINKEDIN = "CHANGE_PROFILE_LINKEDIN";
export const CHANGE_PROFILE_YOUTUBE = "CHANGE_PROFILE_YOUTUBE";
export const CHANGE_PROFILE_INSTAGRAM = "CHANGE_PROFILE_INSTAGRAM";
export const CHANGE_PROFILE_DISPLAY_INPUTS = "CHANGE_PROFILE_DISPLAY_INPUTS";
export const RESET_PROFILE = "RESET_PROFILE";

// Submit Profile Types

export const SUBMIT_PROFILE_DATA = "SUBMIT_PROFILE_DATA";
export const SUBMIT_PROFILE_DATA_SUCCESS = "SUBMIT_PROFILE_DATA_SUCCESS";
export const SUBMIT_PROFILE_DATA_ATTEMPT = "SUBMIT_PROFILE_DATA_ATTEMPT";
export const SUBMIT_PROFILE_DATA_FAIL = "SUBMIT_PROFILE_DATA_FAIL";

// Delete Profile Types

export const DELETE_PROFILE_DATA = "DELETE_PROFILE_DATA";
export const DELETE_PROFILE_DATA_SUCCESS = "DELETE_PROFILE_DATA_SUCCESS";
export const DELETE_PROFILE_DATA_ATTEMPT = "DELETE_PROFILE_DATA_ATTEMPT";
export const DELETE_PROFILE_DATA_FAIL = "DELETE_PROFILE_DATA_FAIL";

// Edit Profile Types

export const EDIT_PROFILE_DATA = "EDIT_PROFILE_DATA";

// Add Experience Input Types

export const CHANGE_EXPERIENCE_COMPANY = "CHANGE_EXPERIENCE_COMPANY";
export const CHANGE_EXPERIENCE_TITLE = "CHANGE_EXPERIENCE_TITLE";
export const CHANGE_EXPERIENCE_LOCATION = "CHANGE_EXPERIENCE_LOCATION";
export const CHANGE_EXPERIENCE_FROM = "CHANGE_EXPERIENCE_FROM";
export const CHANGE_EXPERIENCE_TO = "CHANGE_EXPERIENCE_TO";
export const CHANGE_EXPERIENCE_CURRENT = "CHANGE_EXPERIENCE_CURRENT";
export const CHANGE_EXPERIENCE_DESCRIPTION = "CHANGE_EXPERIENCE_DESCRIPTION";
export const RESET_EXPERIENCE = "RESET_EXPERIENCE";

// Add Experience Types

export const SUBMIT_EXPERIENCE_DATA = "SUBMIT_EXPERIENCE_DATA";
export const SUBMIT_EXPERIENCE_DATA_SUCCESS = "SUBMIT_EXPERIENCE_DATA_SUCCESS";
export const SUBMIT_EXPERIENCE_DATA_ATTEMPT = "SUBMIT_EXPERIENCE_DATA_ATTEMPT";
export const SUBMIT_EXPERIENCE_DATA_FAIL = "SUBMIT_EXPERIENCE_DATA_FAIL";

// Delete Experience Data
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EXPERIENCE_ATTEMPT = "DELETE_EXPERIENCE_ATTEMPT";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAIL = "DELETE_EXPERIENCE_FAIL";
// Add Education Input Types

export const CHANGE_EDUCATION_SCHOOL = "CHANGE_EDUCATION_SCHOOL";
export const CHANGE_EDUCATION_DEGREE = "CHANGE_EDUCATION_DEGREE";
export const CHANGE_EDUCATION_LOCATION = "CHANGE_EDUCATION_LOCATION";
export const CHANGE_EDUCATION_FROM = "CHANGE_EDUCATION_FROM";
export const CHANGE_EDUCATION_TO = "CHANGE_EDUCATION_TO";
export const CHANGE_EDUCATION_CURRENT = "CHANGE_EDUCATION_CURRENT";
export const CHANGE_EDUCATION_DESCRIPTION = "CHANGE_EDUCATION_DESCRIPTION";
export const RESET_EDUCATION = "RESET_EDUCATION";

// Add EDUCATION Types

export const SUBMIT_EDUCATION_DATA = "SUBMIT_EDUCATION_DATA";
export const SUBMIT_EDUCATION_DATA_SUCCESS = "SUBMIT_EDUCATION_DATA_SUCCESS";
export const SUBMIT_EDUCATION_DATA_ATTEMPT = "SUBMIT_EDUCATION_DATA_ATTEMPT";
export const SUBMIT_EDUCATION_DATA_FAIL = "SUBMIT_EDUCATION_DATA_FAIL";

//Delete Education
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const DELETE_EDUCATION_ATTEMPT = "DELETE_EDUCATION_ATTEMPT";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_FAIL";

// Get All Profiles Actions

export const GET_ALL_PROFILE = "GET_ALL_PROFILE";
export const GET_ALL_PROFILE_ATTEMPT = "GET_ALL_PROFILE_ATTEMPT";
export const GET_ALL_PROFILE_SUCCESS = "GET_ALL_PROFILE_SUCCESS";
export const GET_ALL_PROFILE_FAIL = "GET_ALL_PROFILE_FAIL";

// Get Profile By Handle Types

export const GET_PROFILE_HANDLE = "GET_PROFILE_HANDLE";
export const GET_PROFILE_HANDLE_ATTEMPT = "GET_PROFILE_HANDLE_ATTEMPT";
export const GET_PROFILE_HANDLE_SUCCESS = "GET_PROFILE_HANDLE_SUCCESS";
export const GET_PROFILE_HANDLE_FAIL = "GET_PROFILE_HANDLE_FAIL";

//Submit Post
export const SUBMIT_POST = "SUBMIT_POST";
export const SUBMIT_POST_ATTEMPT = "SUBMIT_POST_ATTEMPT";
export const SUBMIT_POST_SUCCESS = "SUBMIT_POST_SUCCESS";
export const SUBMIT_POST_FAIL = "SUBMIT_POST_FAIL";

// onChange Types for post

export const CHANGE_POST = "CHANGE_POST";
export const RESET_POST = "RESET_POST";

//Get Post
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_ATTEMPT = "GET_POSTS_ATTEMPT";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

//Delete Post
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_ATTEMPT = "DELETE_POST_ATTEMPT";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

//  ADD_LIKE Post
export const ADD_LIKE_POST = "ADD_LIKE_POST";
export const ADD_LIKE_POST_ATTEMPT = "ADD_LIKE_POST_ATTEMPT";
export const ADD_LIKE_POST_SUCCESS = "ADD_LIKE_POST_SUCCESS";
export const ADD_LIKE_POST_FAIL = "ADD_LIKE_POST_FAIL";

//REMOVE_LIKE Post
export const REMOVE_LIKE_POST = "REMOVE_LIKE_POST";
export const REMOVE_LIKE_POST_ATTEMPT = "REMOVE_LIKE_POST_ATTEMPT";
export const REMOVE_LIKE_POST_SUCCESS = "REMOVE_LIKE_POST_SUCCESS";
export const REMOVE_LIKE_POST_FAIL = "REMOVE_LIKE_POST_FAIL";

//aDD COMMENT Post
export const ADD_COMMENT_POST = "ADD_COMMENT_POST";
export const ADD_COMMENT_POST_ATTEMPT = "ADD_COMMENT_POST_ATTEMPT";
export const ADD_COMMENT_POST_SUCCESS = "ADD_COMMENT_POST_SUCCESS";
export const ADD_COMMENT_POST_FAIL = "ADD_COMMENT_POST_FAIL";

//REMOVE COMMENT Post
export const REMOVE_COMMENT_POST = "REMOVE_COMMENT_POST";
export const REMOVE_COMMENT_POST_ATTEMPT = "REMOVE_COMMENT_POST_ATTEMPT";
export const REMOVE_COMMENT_POST_SUCCESS = "REMOVE_COMMENT_POST_SUCCESS";
export const REMOVE_COMMENT_POST_FAIL = "REMOVE_COMMENT_POST_FAIL";

//GET SINGLE Post
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const GET_SINGLE_POST_ATTEMPT = "GET_SINGLE_POST_ATTEMPT";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL";

// CHANGE COMMENT TYPES

export const CHANGE_COMMENT = "CHANGE_COMMENT";
export const RESET_COMMENT = "RESET_COMMENT";
